-- Fundación del editor de noticias por bloques.
--
-- Esta migración contempla que algunos entornos ya tienen una versión legado
-- de noticia_bloques (contenido text y media_url). No modifica public.noticias
-- ni elimina media_url: los datos legado se conservan mientras contenido pasa
-- a ser jsonb.

begin;

-- PostgreSQL no ofrece %TYPE en CREATE TABLE. Se obtiene el tipo real de
-- noticias.id para que noticia_id sea exactamente del mismo tipo también en
-- instalaciones nuevas.
do $migration$
declare
  noticias_id_type text;
begin
  if to_regclass('public.noticias') is null then
    raise exception 'public.noticias must exist before creating noticia_bloques';
  end if;

  if to_regclass('public.noticia_bloques') is null then
    select pg_catalog.format_type(attribute.atttypid, attribute.atttypmod)
      into noticias_id_type
    from pg_catalog.pg_attribute as attribute
    where attribute.attrelid = 'public.noticias'::regclass
      and attribute.attname = 'id'
      and attribute.attnum > 0
      and not attribute.attisdropped;

    if noticias_id_type is null then
      raise exception 'public.noticias.id does not exist';
    end if;

    execute format(
      $create_table$
        create table public.noticia_bloques (
          id bigint generated by default as identity primary key,
          noticia_id %s not null,
          tipo text not null,
          orden integer not null,
          contenido jsonb not null default '{}'::jsonb,
          created_at timestamptz not null default now(),
          updated_at timestamptz not null default now()
        )
      $create_table$,
      noticias_id_type
    );
  end if;
end;
$migration$;

-- Verifica también el esquema legado: una FK puede aceptar ciertos tipos
-- compatibles aunque no sean idénticos, pero este modelo exige igualdad.
do $migration$
declare
  noticias_id_type text;
  bloques_noticia_id_type text;
begin
  select pg_catalog.format_type(attribute.atttypid, attribute.atttypmod)
    into noticias_id_type
  from pg_catalog.pg_attribute as attribute
  where attribute.attrelid = 'public.noticias'::regclass
    and attribute.attname = 'id'
    and attribute.attnum > 0
    and not attribute.attisdropped;

  select pg_catalog.format_type(attribute.atttypid, attribute.atttypmod)
    into bloques_noticia_id_type
  from pg_catalog.pg_attribute as attribute
  where attribute.attrelid = 'public.noticia_bloques'::regclass
    and attribute.attname = 'noticia_id'
    and attribute.attnum > 0
    and not attribute.attisdropped;

  if bloques_noticia_id_type is distinct from noticias_id_type then
    raise exception
      'noticia_bloques.noticia_id type (%) differs from noticias.id type (%)',
      bloques_noticia_id_type,
      noticias_id_type;
  end if;
end;
$migration$;

-- Completa las columnas de la versión actual sin tocar la tabla noticias.
alter table public.noticia_bloques
  add column if not exists updated_at timestamptz;

-- Convierte contenido text legado sin depender de que la tabla siga vacía.
-- Los objetos JSON válidos se preservan; texto normal, arrays y escalares JSON
-- se conservan sin pérdida bajo la clave "text".
create or replace function pg_temp.try_parse_jsonb(value text)
returns jsonb
language plpgsql
immutable
strict
as $function$
begin
  return value::jsonb;
exception
  when others then
    return null;
end;
$function$;

do $migration$
declare
  contenido_type text;
begin
  select pg_catalog.format_type(attribute.atttypid, attribute.atttypmod)
    into contenido_type
  from pg_catalog.pg_attribute as attribute
  where attribute.attrelid = 'public.noticia_bloques'::regclass
    and attribute.attname = 'contenido'
    and attribute.attnum > 0
    and not attribute.attisdropped;

  if contenido_type is null then
    alter table public.noticia_bloques
      add column contenido jsonb;
  elsif contenido_type <> 'jsonb' then
    alter table public.noticia_bloques
      alter column contenido type jsonb
      using (
        case
          when contenido is null then '{}'::jsonb
          when jsonb_typeof(pg_temp.try_parse_jsonb(contenido::text)) = 'object'
            then pg_temp.try_parse_jsonb(contenido::text)
          else jsonb_build_object('text', contenido::text)
        end
      );
  end if;
end;
$migration$;

alter table public.noticia_bloques
  alter column contenido set default '{}'::jsonb,
  alter column contenido set not null,
  alter column created_at set default now(),
  alter column created_at set not null,
  alter column updated_at set default now(),
  alter column updated_at set not null;

-- Asegura ON DELETE CASCADE incluso si ya existía una FK sin esa acción.
do $migration$
declare
  existing_fk_name text;
  existing_fk_delete_action "char";
begin
  select constraint_row.conname, constraint_row.confdeltype
    into existing_fk_name, existing_fk_delete_action
  from pg_catalog.pg_constraint as constraint_row
  join pg_catalog.pg_attribute as attribute
    on attribute.attrelid = constraint_row.conrelid
   and attribute.attnum = any (constraint_row.conkey)
  where constraint_row.conrelid = 'public.noticia_bloques'::regclass
    and constraint_row.confrelid = 'public.noticias'::regclass
    and constraint_row.contype = 'f'
    and attribute.attname = 'noticia_id'
  limit 1;

  if existing_fk_name is not null and existing_fk_delete_action <> 'c' then
    execute format(
      'alter table public.noticia_bloques drop constraint %I',
      existing_fk_name
    );
    existing_fk_name := null;
  end if;

  if existing_fk_name is null then
    alter table public.noticia_bloques
      add constraint noticia_bloques_noticia_id_fkey
      foreign key (noticia_id)
      references public.noticias (id)
      on delete cascade;
  end if;
end;
$migration$;

-- Elimina cualquier CHECK legado que involucre tipo (el nombre real de esa
-- constraint no está versionado) antes de instalar el vocabulario nuevo.
do $migration$
declare
  legacy_tipo_constraint record;
  tipo_attribute_number smallint;
begin
  select attribute.attnum
    into tipo_attribute_number
  from pg_catalog.pg_attribute as attribute
  where attribute.attrelid = 'public.noticia_bloques'::regclass
    and attribute.attname = 'tipo'
    and attribute.attnum > 0
    and not attribute.attisdropped;

  for legacy_tipo_constraint in
    select constraint_row.conname
    from pg_catalog.pg_constraint as constraint_row
    where constraint_row.conrelid = 'public.noticia_bloques'::regclass
      and constraint_row.contype = 'c'
      and tipo_attribute_number = any (constraint_row.conkey)
  loop
    execute format(
      'alter table public.noticia_bloques drop constraint %I',
      legacy_tipo_constraint.conname
    );
  end loop;
end;
$migration$;

alter table public.noticia_bloques
  drop constraint if exists noticia_bloques_orden_check,
  drop constraint if exists noticia_bloques_contenido_object_check,
  drop constraint if exists noticia_bloques_video_provider_check;

alter table public.noticia_bloques
  add constraint noticia_bloques_tipo_check
    check (tipo in ('paragraph', 'image', 'gallery', 'video')),
  add constraint noticia_bloques_orden_check
    check (orden >= 0),
  add constraint noticia_bloques_contenido_object_check
    check (jsonb_typeof(contenido) = 'object'),
  add constraint noticia_bloques_video_provider_check
    check (
      tipo <> 'video'
      or coalesce(
        contenido ->> 'provider' in ('youtube', 'instagram', 'tiktok'),
        false
      )
    );

-- Este índice único también resuelve eficientemente ORDER BY orden para una
-- noticia y evita posiciones ambiguas. El reordenamiento puede hacerse en una
-- transacción usando valores temporales fuera del rango final.
create unique index noticia_bloques_noticia_id_orden_key
  on public.noticia_bloques (noticia_id, orden);

-- El índice compuesto comienza por noticia_id y mantiene orden como segunda
-- clave, por lo que reemplaza los dos B-tree legado sin afectar la PK.
drop index if exists public.idx_bloques_noticia;
drop index if exists public.idx_bloques_orden;

create or replace function public.set_noticia_bloque_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $function$
begin
  new.updated_at = now();
  return new;
end;
$function$;

drop trigger if exists noticia_bloques_set_updated_at
  on public.noticia_bloques;

create trigger noticia_bloques_set_updated_at
before update on public.noticia_bloques
for each row
execute function public.set_noticia_bloque_updated_at();

alter table public.noticia_bloques enable row level security;

-- Las policies legado son desconocidas porque su migración no está en el
-- repositorio. Se eliminan todas para que ninguna policy permisiva anterior
-- pueda ampliar el acceso definido abajo.
do $migration$
declare
  existing_policy record;
begin
  for existing_policy in
    select policyname
    from pg_catalog.pg_policies
    where schemaname = 'public'
      and tablename = 'noticia_bloques'
  loop
    execute format(
      'drop policy %I on public.noticia_bloques',
      existing_policy.policyname
    );
  end loop;
end;
$migration$;

-- La lectura hereda exactamente la visibilidad RLS de la noticia padre:
-- público para noticias publicadas y acceso editorial/propio según las
-- policies vigentes de public.noticias.
create policy "noticia_bloques_select_via_noticia"
  on public.noticia_bloques
  for select
  using (
    exists (
      select 1
      from public.noticias as noticia
      where noticia.id = noticia_bloques.noticia_id
    )
  );

-- La autorización editorial reutiliza las mismas vistas empleadas por las
-- policies de noticias. Como sus definiciones no están versionadas, se
-- consultan ambas explícitamente: esto cubre tanto el caso en que
-- v_is_editor ya incluye admin como aquel en que cada vista representa un rol.
-- El rol vigente de autor es "colaborador": sólo puede trabajar sobre sus
-- propios borradores, igual que en el editor actual.
create policy "noticia_bloques_insert_editorial"
  on public.noticia_bloques
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.v_is_editor as editor
      where editor.id = (select auth.uid())
    )
    or exists (
      select 1
      from public.v_is_admin as administrator
      where administrator.id = (select auth.uid())
    )
    or exists (
      select 1
      from public.noticias as noticia
      where noticia.id = noticia_bloques.noticia_id
        and noticia.owner_id = (select auth.uid())
        and noticia.estado = 'borrador'
    )
  );

create policy "noticia_bloques_update_editorial"
  on public.noticia_bloques
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.v_is_editor as editor
      where editor.id = (select auth.uid())
    )
    or exists (
      select 1
      from public.v_is_admin as administrator
      where administrator.id = (select auth.uid())
    )
    or exists (
      select 1
      from public.noticias as noticia
      where noticia.id = noticia_bloques.noticia_id
        and noticia.owner_id = (select auth.uid())
        and noticia.estado = 'borrador'
    )
  )
  with check (
    exists (
      select 1
      from public.v_is_editor as editor
      where editor.id = (select auth.uid())
    )
    or exists (
      select 1
      from public.v_is_admin as administrator
      where administrator.id = (select auth.uid())
    )
    or exists (
      select 1
      from public.noticias as noticia
      where noticia.id = noticia_bloques.noticia_id
        and noticia.owner_id = (select auth.uid())
        and noticia.estado = 'borrador'
    )
  );

create policy "noticia_bloques_delete_editorial"
  on public.noticia_bloques
  for delete
  to authenticated
  using (
    exists (
      select 1
      from public.v_is_editor as editor
      where editor.id = (select auth.uid())
    )
    or exists (
      select 1
      from public.v_is_admin as administrator
      where administrator.id = (select auth.uid())
    )
    or exists (
      select 1
      from public.noticias as noticia
      where noticia.id = noticia_bloques.noticia_id
        and noticia.owner_id = (select auth.uid())
        and noticia.estado = 'borrador'
    )
  );

revoke all on table public.noticia_bloques from anon, authenticated;
grant select on table public.noticia_bloques to anon;
grant select, insert, update, delete on table public.noticia_bloques to authenticated;

comment on table public.noticia_bloques is
  'Contenido estructurado y ordenado de noticias; noticias.contenido se conserva como fallback legado.';
comment on column public.noticia_bloques.contenido is
  'Payload JSON del bloque. Los embeds almacenan provider y URL, nunca HTML provisto por usuarios.';

commit;
